

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jared
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jared
 */

import com.the_best_Fast_Payment.pay;


public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
     
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtmonto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        boxpagos = new javax.swing.JComboBox<>();
        btncalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Arearesultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Monto:");

        jLabel2.setText("Descripción:");

        jLabel3.setText("Tipo de Pago:");

        boxpagos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Transferencia" }));

        btncalcular.setText("Calcular Total");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        Arearesultado.setColumns(20);
        Arearesultado.setRows(5);
        jScrollPane1.setViewportView(Arearesultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxpagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btncalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(boxpagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btncalcular)
                        .addContainerGap(173, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
       
         try {
        // Obtener los datos del usuario
        double monto = Double.parseDouble(txtmonto.getText());
        String descripcion = txtdescripcion.getText();

        // Validar monto y descripción
        pay.validarMonto(monto);
        pay.validarDescripcion(descripcion);

        // Calcular el total según el tipo de pago
        double total = 0;
        String tipoPago = boxpagos.getSelectedItem().toString();
        String descuentoInfo = "";  // Variable para mostrar el descuento
        String comisionInfo = "";   // Variable para mostrar la comisión

        switch (tipoPago) {
            case "Efectivo":
                total = pay.calcularPagoEfectivo(monto);
                // Solo se agrega el mensaje de descuento si se aplica
                if (monto > 500) {
                    descuentoInfo = "✅ Descuento aplicado: 5% por monto mayor a $500\n"; // Este es solo el mensaje
                }
                break;
            case "Tarjeta":
                total = pay.calcularPagoTarjeta(monto);
                comisionInfo = "💳 Comisión del 3% aplicada por pago con tarjeta.\n"; // Mensaje de comisión para tarjeta
                break;
            case "Transferencia":
                total = pay.calcularPagoTransferencia(monto);
                comisionInfo = "💰 Comisión fija de $15 aplicada por pago con transferencia.\n"; // Mensaje de comisión para transferencia
                break;
            default:
                Arearesultado.setText("❌ Tipo de pago no válido.");
                return;
        }

        // Calcular el IVA
        double iva = pay.calcularIVA(total);

        // Mostrar el resultado en el área de texto
        String resumen = "RESUMEN DE LA TRANSACCIÓN \n\n" +
                         "Descripción: " + descripcion + "\n" +
                         "Tipo de Pago: " + tipoPago + "\n" +
                         "Monto: $" + String.format("%.2f", monto) + "\n" +
                         descuentoInfo +  // Aquí añadimos solo el mensaje de descuento
                         comisionInfo +    // Aquí añadimos el mensaje de la comisión
                         "IVA (16%): $" + String.format("%.2f", iva) + "\n" +
                         "Total: $" + String.format("%.2f", total + iva);

        Arearesultado.setText(resumen);

    }catch (IllegalArgumentException e) {
        // En caso de que haya una excepción de validación
        Arearesultado.setText("❌ Error: " + e.getMessage());
    }
        // En caso de que no se haya ingresado un monto válido
        
      
        
        

    }//GEN-LAST:event_btncalcularActionPerformed

    




       public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Cliente().setVisible(true);
        });
}
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Arearesultado;
    private javax.swing.JComboBox<String> boxpagos;
    private javax.swing.JButton btncalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtmonto;
    // End of variables declaration//GEN-END:variables
}